from __future__ import annotations

from .agent import ToolRegistry, ToolSpec
from .toolkit import FortyGuardToolkit


def build_tool_registry(toolkit: FortyGuardToolkit) -> ToolRegistry:
    """Register only narrow, typed tools; raw HTTP is never exposed to an agent."""
    registry = ToolRegistry()
    registry.register(ToolSpec("inspect_shift_plan", "Inspect a submitted upcoming-shift plan.", {"type": "object", "properties": {"tasks": {"type": "array"}}, "required": ["tasks"]}, toolkit.inspect_shift_plan))
    registry.register(ToolSpec("identify_thermal_candidates", "Select movable outdoor tasks that justify thermal investigation.", {"type": "object", "properties": {"tasks": {"type": "array"}}, "required": ["tasks"]}, toolkit.identify_thermal_candidates))
    evidence_ids = ["phoenix_canonical_2025_07_15_1000_1200", "phoenix_contextual_tcm_v1", "phoenix_unavailable_probe_v1"]
    evidence_schema = {"type": "object", "properties": {"evidence_id": {"type": "string", "enum": evidence_ids}, "workfaces": {"type": "array", "items": {"type": "string"}}, "window": {"type": "string"}, "analytic_type": {"type": "string", "enum": ["tcm", "time_of_measure", "exceedance", "persistence"]}}, "required": ["evidence_id"], "additionalProperties": False}
    registry.register(ToolSpec("get_workface_thermal_evidence", "Resolve compact evidence from the approved manifest by ID; never accepts a path or submits a request.", evidence_schema, toolkit.get_workface_thermal_evidence))
    registry.register(ToolSpec("get_workface_heatmap", "Resolve compact evidence from the approved manifest by ID; never accepts a path or submits a request.", evidence_schema, toolkit.get_workface_thermal_evidence))
    registry.register(ToolSpec("get_environmental_context", "Resolve optional context from the approved manifest by ID.", {"type": "object", "properties": {"evidence_id": {"type": "string", "enum": evidence_ids}}, "required": ["evidence_id"], "additionalProperties": False}, toolkit.get_environmental_context))
    registry.register(ToolSpec("acquire_workface_thermal_evidence", "Request and validate decision-grade FortyGuard exceedance evidence for a validated operator-created site. Credentials, HTTP, polling, cache, and provenance remain backend-owned.", {"type": "object", "properties": {"project_id": {"type": "string"}, "polygon_aoi": {"type": "object"}, "workfaces": {"type": "array"}, "date": {"type": "string"}, "timezone": {"type": "string"}, "start_time": {"type": "string"}, "end_time": {"type": "string"}, "threshold": {"type": "number", "enum": [32]}, "analytic_type": {"type": "string", "enum": ["exceedance"]}, "direction": {"type": "string", "enum": ["above"]}, "granularity": {"type": "integer", "enum": [60, 80, 100]}}, "required": ["project_id", "polygon_aoi", "workfaces", "date", "timezone", "start_time", "end_time", "threshold", "analytic_type", "direction", "granularity"], "additionalProperties": False}, lambda args: toolkit.acquire_workface_thermal_evidence(args)))
    registry.register(ToolSpec("calculate_thermal_overlap", "Calculate scheduled overlap with the employer trigger.", {"type": "object", "required": ["task_start", "task_end", "trigger_name", "trigger_start", "trigger_end", "crew_size"]}, toolkit.calculate_thermal_overlap))
    registry.register(ToolSpec("generate_feasible_schedule_alternatives", "Generate and verify deterministic feasible schedule candidates.", {"type": "object", "properties": {"tasks": {"type": "array"}, "crews": {"type": "object"}, "baseline": {"type": "object"}, "schedule": {"type": "object"}, "policy": {"type": "object"}, "shift_start": {}, "shift_end": {}, "trigger_start": {}, "trigger_end": {}}, "required": ["tasks", "crews", "baseline", "shift_start", "shift_end", "trigger_start", "trigger_end"], "additionalProperties": False}, toolkit.generate_feasible_schedule_alternatives))
    registry.register(ToolSpec("calculate_scheduled_high_heat_crew_hours", "Calculate SHHCH from schedule-aligned FortyGuard exceedance windows and polygon workfaces.", {"type": "object", "required": ["schedule", "workfaces", "exceedance_windows", "project_thermal_trigger"], "properties": {"schedule": {"type": "object"}, "workfaces": {"type": "array"}, "exceedance_windows": {"type": "array"}, "project_thermal_trigger": {"type": "object"}}, "additionalProperties": False}, toolkit.calculate_scheduled_high_heat_crew_hours))
    registry.register(ToolSpec("verify_schedule", "Verify a candidate schedule against every hard constraint.", {"type": "object", "properties": {"tasks": {"type": "array"}, "schedule": {"type": "object"}, "source_schedule": {"type": "object"}, "crews": {"type": "object"}, "policy": {"type": "object"}, "break_reservations": {"type": "array"}, "evidence": {"type": "object"}, "shift_start": {}, "shift_end": {}, "trigger_start": {}, "trigger_end": {}, "require_thermal_evidence": {"type": "boolean"}, "thermal_evidence_valid": {"type": "boolean"}}, "required": ["tasks", "schedule", "crews", "policy", "shift_start", "shift_end", "trigger_start", "trigger_end"], "additionalProperties": False}, toolkit.verify_schedule))
    registry.register(ToolSpec("compare_schedule_metrics", "Compare derived schedule metrics with provenance.", {"type": "object", "required": ["before_crew_hours", "after_crew_hours"]}, toolkit.compare_schedule_metrics))
    registry.register(ToolSpec("request_superintendent_approval", "Create the human approval gate; never publish a plan.", {"type": "object", "required": ["recommendation_id", "candidate_hash"], "properties": {"recommendation_id": {"type": "string"}, "candidate_hash": {"type": "string"}}, "additionalProperties": False}, toolkit.request_superintendent_approval, requires_approval=True))
    registry.register(ToolSpec("recheck_thermal_evidence", "Explicitly recheck unavailable evidence without reusing invalid data.", {"type": "object", "properties": {"current_schedule": {"type": "object"}}, "required": ["current_schedule"], "additionalProperties": False}, toolkit.recheck_thermal_evidence))
    registry.register(ToolSpec("summarize_heat_profile", "Derive a transparent summary from permitted thermal samples.", {"type": "object"}, toolkit.summarize_heat_profile))
    registry.register(ToolSpec("compare_locations", "Compare candidate location profiles with the same derived metric.", {"type": "object"}, toolkit.compare_locations))
    registry.register(ToolSpec("calculate_contextual_temperature_summary", "Summarize contextual temperature samples; never supplies SHHCH evidence.", {"type": "object"}, toolkit.calculate_contextual_temperature_summary))
    return registry
