import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, Check, ChevronRight, ClipboardCheck, Clock3, Database, Eye, HardHat, Layers3, LockKeyhole, MapPin, Play, RotateCcw, ShieldCheck, ThermometerSun, Users, X } from 'lucide-react'
import { CREWS, EMPLOYER_POLICY, TASKS, THERMAL_EVIDENCE, type Task, timelinePosition, timelineWidth } from './demo/scenario'
import { CANONICAL_RUN, agentAudit, approveRecommendation, runCrewClock, type CrewClockRun, type EvidenceState, type Schedule } from './demo/engine'

type PlanView = 'original' | 'proposed'
type DrawerView = 'evidence' | 'audit' | null
const STAGES = [
  ['Checking tomorrow’s work', '14 tasks · 3 crews · constraints loaded', 'lookahead.inspect'],
  ['Selecting affected work', '7 movable outdoor tasks · 2 shaded tasks skipped', 'work.classify'],
  ['Comparing thermal timing', '2 affected workfaces · cached-live evidence', 'fortyguard.cached_evidence'],
  ['Testing schedule alternatives', `${CANONICAL_RUN.stats.candidatesConsidered.toLocaleString()} deterministic schedules evaluated`, 'schedule.optimize'],
  ['Checking hard constraints', 'Fixed work · logic · crews · deadlines · policy', 'constraints.verify'],
  ['Recommendation ready', '22 → 6 modeled peak-window crew-hours', 'recommendation.prepare'],
  ['Approved plan verified', 'Human decision recorded · result recomputed', 'result.verify'],
] as const

const getRunMode = (): CrewClockRun => {
  const mode = new URLSearchParams(window.location.search).get('mode')
  const evidence: Record<string, EvidenceState> = { 'missing-evidence': 'missing', 'stale-evidence': 'stale', 'tool-failure': 'tool-failure' }
  if (mode && evidence[mode]) return runCrewClock({ evidenceState: evidence[mode] })
  if (mode === 'ambiguous-policy') return runCrewClock({ policyState: 'ambiguous' })
  if (mode === 'no-improvement') return runCrewClock({ tasks: TASKS.map(task => ({ ...task, fixed: true, proposedStart: task.originalStart })) })
  return CANONICAL_RUN
}

function SourceTag({ children, tone = 'lime' }: { children: React.ReactNode; tone?: 'lime' | 'orange' | 'blue' | 'gray' }) {
  return <span className={`source-tag ${tone}`}>{children}</span>
}

function ThermalProfile({ active }: { active: boolean }) {
  const values = THERMAL_EVIDENCE.apparentTemperatureC.slice(5, 17)
  const points = values.map((value, index) => `${index / (values.length - 1) * 100},${56 - (value - 27) / 17 * 47}`).join(' ')
  return <section className={`thermal-panel ${active ? 'active' : ''}`}>
    <div className="panel-title"><div><SourceTag>FORTYGUARD · CACHED LIVE</SourceTag><h2>Thermal timing</h2></div><Eye size={15}/></div>
    <div className="thermal-summary"><span><strong>42.5°C</strong><small>apparent peak · 13:00</small></span><span><strong>11–15</strong><small>highest modeled window</small></span></div>
    <div className="thermal-chart"><div className="thermal-window"><span>PEAK WINDOW</span></div><svg viewBox="0 0 100 60" preserveAspectRatio="none" aria-label="Cached hourly apparent-temperature profile"><defs><linearGradient id="thermalArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff824d" stopOpacity=".55"/><stop offset="1" stopColor="#ff824d" stopOpacity="0"/></linearGradient></defs><polygon points={`0,59 ${points} 100,59`} fill="url(#thermalArea)"/><polyline points={points} fill="none" stroke="#ff9d57" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/></svg><div className="axis"><span>05</span><span>08</span><span>11</span><span>14</span><span>16</span></div></div>
    <p className="fineprint">Historical Phoenix replay · 15 Jul 2025 · planning evidence, not onsite conditions</p>
  </section>
}

function SiteMap({ active }: { active: boolean }) {
  return <section className={`map-panel ${active ? 'active' : ''}`}><div className="panel-title"><div><SourceTag tone="gray">DEMO INPUT</SourceTag><h2>Workfaces</h2></div><MapPin size={16}/></div><div className="site-map"><svg viewBox="0 0 420 258" role="img" aria-label="Illustrative Phoenix construction workfaces"><defs><radialGradient id="heatNorth"><stop stopColor="#ff6c42" stopOpacity=".72"/><stop offset="1" stopColor="#ff6c42" stopOpacity="0"/></radialGradient><radialGradient id="heatSouth"><stop stopColor="#ff9d57" stopOpacity=".62"/><stop offset="1" stopColor="#ff9d57" stopOpacity="0"/></radialGradient><pattern id="siteGrid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#566056" strokeWidth=".5"/></pattern></defs><rect width="420" height="258" fill="url(#siteGrid)" opacity=".36"/><circle className="heat-spot" cx="192" cy="82" r="130" fill="url(#heatNorth)"/><circle className="heat-spot" cx="306" cy="188" r="105" fill="url(#heatSouth)"/><path className="road" d="M-15 225C86 170 155 193 228 142S350 78 440 61"/><path className="road minor" d="M71-12L143 270M359-10L302 270"/><g className="workface north"><rect x="98" y="45" width="150" height="72" rx="4"/><text x="114" y="70">NORTH WORKFACE</text><text x="114" y="91">4 TASKS INVESTIGATED</text><circle cx="230" cy="64" r="4"/></g><g className="workface south"><rect x="245" y="146" width="150" height="70" rx="4"/><text x="261" y="171">SOUTH WORKFACE</text><text x="261" y="192">3 TASKS INVESTIGATED</text><circle cx="378" cy="165" r="4"/></g><g className="workface laydown"><rect x="32" y="173" width="130" height="54" rx="4"/><text x="47" y="195">LAYDOWN · SHADE</text><text x="47" y="214">2 TASKS SKIPPED</text></g></svg><div className="map-scan"><i/></div></div><div className="map-legend"><span><i className="investigated"/>Investigated</span><span><i className="skipped"/>Thermally skipped</span></div></section>
}

function TaskBlock({ task, schedule, original, showMove }: { task: Task; schedule: Schedule; original: Schedule; showMove: boolean }) {
  const start = schedule[task.id]
  return <div className={`task-block ${task.environment} ${task.fixed ? 'fixed' : ''} ${start !== original[task.id] && showMove ? 'moved' : ''}`} style={{ left: `${timelinePosition(start)}%`, width: `${timelineWidth(task.durationMinutes)}%` }} title={`${task.id} · ${task.name} · ${start} · ${task.durationMinutes} minutes`}>{task.fixed && <LockKeyhole size={9}/>}<span>{task.id} · {task.name}</span><small>{start}</small></div>
}

function ScheduleBoard({ run, plan, revealed, verified, onPlan }: { run: CrewClockRun; plan: PlanView; revealed: boolean; verified: boolean; onPlan: (plan: PlanView) => void }) {
  const schedule = plan === 'proposed' && run.recommendation ? run.recommendation : run.original
  const changed = TASKS.filter(task => run.recommendation && run.recommendation[task.id] !== run.original[task.id])
  return <section className={`schedule-panel ${plan === 'proposed' ? 'proposed' : ''}`}><div className="schedule-heading"><div><SourceTag tone={plan === 'proposed' ? 'lime' : 'gray'}>{plan === 'proposed' ? 'CREWCLOCK PLAN' : 'ORIGINAL PLAN'}</SourceTag><h2>Tomorrow’s crew schedule</h2></div><div className="plan-switch" role="group" aria-label="Compare schedules"><button className={plan === 'original' ? 'active' : ''} onClick={() => onPlan('original')}>Original <b>22h</b></button><button disabled={!revealed} className={plan === 'proposed' ? 'active' : ''} onClick={() => onPlan('proposed')}>CrewClock <b>{revealed ? '6h' : '—'}</b></button></div></div><div className="timeline-head"><span>05:30</span><span>08:00</span><span>11:00</span><span>13:00</span><span>15:00</span></div><div className="schedule-grid"><div className="peak-band"><span>HIGHEST MODELED HEAT</span></div>{CREWS.map(crew => <div className="crew-row" key={crew.id}><div className="crew-label"><i style={{ background: crew.color }}/><span><strong>{crew.name}</strong><small>{crew.trade} · {crew.headcount}</small></span></div><div className="crew-track">{TASKS.filter(task => task.crewId === crew.id).map(task => <TaskBlock key={task.id} task={task} schedule={schedule} original={run.original} showMove={revealed}/>)}</div></div>)}</div><div className="schedule-key"><span><i className="outdoor"/>Outdoor</span><span><i className="support"/>Shaded/support</span><span><LockKeyhole size={10}/>Fixed</span><span className={verified ? 'pass' : ''}><Check size={11}/>{verified ? '6/6 constraint families pass' : '14 tasks retained'}</span></div><div className={`change-strip ${revealed ? 'visible' : ''}`}><div><SourceTag tone="orange">DERIVED</SourceTag><strong>{revealed ? changed.length : '—'} tasks retimed</strong><small>Thermal objective remains subordinate to hard constraints.</small></div><div className="change-list">{revealed && changed.map(task => <span key={task.id}><b>{task.id}</b> {run.original[task.id]} <ArrowRight/> {run.recommendation?.[task.id]}</span>)}</div></div></section>
}

function AgentPanel({ run, stage, running, approved, onRun, onApprove, onAudit }: { run: CrewClockRun; stage: number; running: boolean; approved: boolean; onRun: () => void; onApprove: () => void; onAudit: () => void }) {
  const revealed = stage >= 5 && run.status === 'recommended'; const verified = stage >= 6 && approved; const failure = stage >= 2 && run.status !== 'recommended'; const visibleStages = failure ? STAGES.slice(0, 3) : STAGES
  return <aside className="agent-panel"><div className="agent-title"><div><SourceTag>AGENT RUN · CC-PHX-0716</SourceTag><h2>{failure ? 'Guardrail engaged' : verified ? 'Plan verified' : revealed ? 'Decision required' : running ? 'CrewClock is working' : 'Ready for tomorrow'}</h2></div><span className={`agent-pulse ${running ? 'running' : ''}`}><Layers3 size={16}/></span></div><div className="progress"><i style={{ width: `${Math.max(0, (stage + 1) / visibleStages.length * 100)}%` }}/></div><ol className="agent-stages">{visibleStages.map((item, index) => <li key={item[0]} className={index < stage || verified ? 'done' : index === stage ? 'current' : ''}><span className="stage-index">{index < stage || verified ? <Check size={11}/> : String(index + 1).padStart(2, '0')}</span><div><strong>{item[0]}</strong><small>{index <= stage ? item[1] : item[2]}</small></div></li>)}</ol>{failure && <div className="guardrail"><AlertTriangle/><div><strong>No schedule change issued</strong><small>{run.message}</small></div></div>}{!running && stage < 0 && <button id="run-plan" className="primary-action" onClick={onRun}><Play size={14} fill="currentColor"/>Run tomorrow’s plan</button>}{revealed && !approved && <div className="approval-box"><div className="decision-metric"><span>PROPOSED IMPROVEMENT</span><strong>{run.shiftedCrewHours}</strong><small>crew-hours shifted</small></div><ul><li><Check/> {run.recommendationVerification?.passedFamilies}/6 hard-constraint families pass</li><li><Check/> 5 fixed commitments unchanged</li><li><Check/> Assumptions and evidence attached</li></ul><button id="approve-plan" onClick={onApprove}><ShieldCheck size={15}/>Approve tomorrow’s plan</button></div>}{verified && <div className="hero-result"><span><Check/> APPROVED · VERIFIED</span><strong>{run.shiftedCrewHours}</strong><h3>CREW-HOURS<br/>SHIFTED</h3><p>out of the highest modeled heat window</p><small>DERIVED planning metric · not a safety outcome</small></div>}{(stage >= 0 || failure) && <button className="audit-link" onClick={onAudit}>Open factual audit trail <ChevronRight size={13}/></button>}</aside>
}

function Inspector({ view, run, approved, onClose }: { view: DrawerView; run: CrewClockRun; approved: boolean; onClose: () => void }) {
  const audit = agentAudit(run, approved)
  return <><div className={`drawer-backdrop ${view ? 'open' : ''}`} onClick={onClose}/><aside className={`inspector ${view ? 'open' : ''}`} aria-hidden={!view}><div className="inspector-head"><div><SourceTag>{view === 'audit' ? 'FACTUAL ACTIONS ONLY' : 'EVIDENCE INSPECTOR'}</SourceTag><h2>{view === 'audit' ? 'Agent audit trail' : 'Why this plan?'}</h2></div><button className="plain-icon" onClick={onClose} aria-label="Close inspector"><X/></button></div>{view === 'audit' ? <div className="audit-list">{audit.map((event, index) => <article key={`${event.time}-${index}`}><time>{event.time}</time><div><strong>{event.action}</strong><SourceTag tone={event.source.includes('FORTYGUARD') ? 'lime' : event.source === 'DERIVED' ? 'orange' : 'gray'}>{event.source}</SourceTag></div></article>)}</div> : <><section className="inspector-block"><SourceTag>FORTYGUARD · CACHED LIVE</SourceTag><dl><dt>AOI</dt><dd>{THERMAL_EVIDENCE.location}</dd><dt>Observation</dt><dd>{THERMAL_EVIDENCE.observationDate} · {THERMAL_EVIDENCE.timezone}</dd><dt>Temperature map</dt><dd>max {THERMAL_EVIDENCE.maxTemperatureC}°C · avg {THERMAL_EVIDENCE.averageTemperatureC}°C</dd><dt>Hourly context</dt><dd>42.5°C apparent peak · 13:00</dd><dt>Spatial analysis</dt><dd>{THERMAL_EVIDENCE.timeOfMeasureCells} cells · {THERMAL_EVIDENCE.grid}</dd></dl></section><section className="inspector-block"><SourceTag tone="orange">DERIVED</SourceTag><dl><dt>Eligible work</dt><dd>7 movable outdoor tasks</dd><dt>Original overlap</dt><dd>{run.beforeCrewHours} crew-hours</dd><dt>Proposed overlap</dt><dd>{run.afterCrewHours ?? '—'} crew-hours</dd><dt>Shifted</dt><dd>{run.shiftedCrewHours} crew-hours</dd><dt>Verifier</dt><dd>{run.recommendationVerification?.passedFamilies ?? '—'}/6 families</dd></dl></section><section className="inspector-block"><SourceTag tone="blue">EMPLOYER POLICY</SourceTag><strong>{EMPLOYER_POLICY.name}</strong><ul>{EMPLOYER_POLICY.planningRules.slice(0, 4).map(rule => <li key={rule}>{rule}</li>)}</ul></section><section className="inspector-block"><SourceTag tone="gray">DEMO INPUT</SourceTag><p>The work package, crew assignments, deadlines, qualifications, workface geometry, and employer policy are synthetic scenario inputs—not customer records.</p></section><div className="authority-note"><ShieldCheck/><p><strong>Human authority preserved.</strong> {EMPLOYER_POLICY.authorityBoundary}</p></div><div className="cache-paths"><Database/><div><strong>Sanitized local cache · no network calls</strong>{THERMAL_EVIDENCE.cachePaths.map(path => <small key={path}>{path}</small>)}</div></div></>}</aside></>
}

export default function App() {
  const [run] = useState(getRunMode); const [stage, setStage] = useState(-1); const [running, setRunning] = useState(false); const [approved, setApproved] = useState(false); const [plan, setPlan] = useState<PlanView>('original'); const [drawer, setDrawer] = useState<DrawerView>(null)
  const revealed = stage >= 5 && run.status === 'recommended'; const verified = stage >= 6 && approved; const investigating = running && stage >= 1 && stage <= 4
  useEffect(() => { if (!running) return; const stopAt = run.status === 'recommended' ? 5 : 2; const timer = window.setTimeout(() => { const next = stage + 1; setStage(next); if (next >= stopAt) { setRunning(false); if (run.status === 'recommended') setPlan('proposed') } }, 620); return () => window.clearTimeout(timer) }, [running, stage, run.status])
  const start = () => { setStage(0); setRunning(true); setApproved(false); setPlan('original') }; const approve = () => { const decision = approveRecommendation(run); if (!decision.approved) return; setApproved(true); window.setTimeout(() => { setStage(6); setPlan('proposed') }, 420) }; const reset = () => { setStage(-1); setRunning(false); setApproved(false); setPlan('original'); setDrawer(null) }
  const status = verified ? 'APPROVED · VERIFIED' : revealed ? 'AWAITING APPROVAL' : running ? 'AGENT INVESTIGATING' : stage >= 0 && run.status !== 'recommended' ? 'NO CHANGE ISSUED' : 'READY TO PLAN'
  return <main className="app-shell" data-state={verified ? 'verified' : revealed ? 'proposed' : investigating ? 'investigating' : 'initial'}><header className="topbar"><div className="brand"><span className="brand-mark"><Clock3 size={15}/></span><span>CREWCLOCK<small>FIELD PLANNING</small></span></div><div className="system-status"><i/>FORTYGUARD CACHE READY <span>·</span> LIVE CALLS 0</div><button onClick={() => setDrawer('evidence')}><Database size={14}/>Evidence</button><button onClick={() => setDrawer('audit')}><ClipboardCheck size={14}/>Audit</button><button className="reset-control" onClick={reset}><RotateCcw size={13}/>Reset</button></header><section className="day-brief"><div className="date-lockup"><span>TOMORROW</span><strong>WED · JUL 16</strong><small>Shift 05:30–14:30 · Phoenix, AZ</small></div><div className="project-lockup"><span>PROJECT</span><strong>ADOT SR-202 SIGNAL PACKAGE</strong><small>Traffic systems · PHX-SIG-04</small></div><div className="brief-stat"><HardHat/><span><strong>14</strong><small>tasks</small></span></div><div className="brief-stat"><Users/><span><strong>3 / 15</strong><small>crews / people</small></span></div><div className="brief-stat hot"><ThermometerSun/><span><strong>11–15</strong><small>modeled peak</small></span></div><div className={`day-status ${verified ? 'verified' : ''}`}><span>{status}</span><strong>{verified ? `${run.shiftedCrewHours}h SHIFTED` : revealed ? 'DECISION READY' : '22h IN PEAK WINDOW'}</strong><small>{verified ? 'derived result · constraints pass' : 'tomorrow’s source plan'}</small></div></section><section className="operations-grid"><div className="evidence-column"><SiteMap active={investigating}/><ThermalProfile active={stage >= 2}/></div><ScheduleBoard run={run} plan={plan} revealed={revealed || verified} verified={verified} onPlan={setPlan}/><AgentPanel run={run} stage={stage} running={running} approved={approved} onRun={start} onApprove={approve} onAudit={() => setDrawer('audit')}/></section><footer className="bottomline"><span>CC-PHX-0716-v1 · deterministic replay</span><span><ShieldCheck size={11}/>Planning support ≠ compliance or safety certification</span><span>FortyGuard evidence: cached-live · schedule: demo input · result: derived</span></footer><Inspector view={drawer} run={run} approved={approved} onClose={() => setDrawer(null)}/></main>
}
